import os
#env = Environment(F90='gfortran', LINK='gfortran', F90FLAGS='-Ofast -funroll-loops -march=native -Jobj')
env = Environment(F90='gfortran', LINK='gfortran', F90FLAGS='-O2 -march=native -Jobj')
sources = Glob('*.f90')
env.Object(sources)
