import os
env = Environment(F90='gfortran', LINK='gfortran', F90FLAGS='-Jobj -march=native -O3 -fopenmp')
#env = Environment(F90='gfortran', LINK='gfortran', F90FLAGS='-Jobj -march=native -Wall -pg')
sources = Glob('*.f90')
env.Object(sources)
